import { expect, test } from '@playwright/test';

async function signIn(page: import('@playwright/test').Page) { await page.addInitScript(() => window.localStorage.setItem('esign.auth', JSON.stringify({ tokens: { accessToken: 'ux005' }, user: { id: 1, email: 'admin@example.test', role: 'super_admin' }, tenant: { id: 1, name: 'UX', plan: 'test', status: 'active' }, permissions: [] }))); }

test('UX-005 guides document, workflow, participants and review while retaining values', async ({ page }) => {
  await signIn(page); let creates = 0;
  await page.route('http://127.0.0.1:4010/**', route => { const url = route.request().url(); if (url.includes('/tenants/me')) return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ tenant: { id: 1, name: 'UX', status: 'active' } }) }); if (url.includes('/permissions')) return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ permissions: [] }) }); if (url.includes('/document-types')) return route.fulfill({ contentType: 'application/json', body: JSON.stringify([{ id: 7, name: 'Hợp đồng', code: 'HD', require_digital_signing: true, require_approval: false, default_workflow_id: null, allow_workflow_override: false, is_active: true }]) }); if (url.includes('/documents') && route.request().method() === 'POST') { creates += 1; return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ document: { sign_request_id: 42 } }) }); } return route.fulfill({ contentType: 'application/json', body: JSON.stringify([]) }); });
  await page.goto('/sign-requests/create'); await page.getByRole('button', { name: 'Tiếp tục' }).press('Enter'); await expect(page.getByText('Vui lòng chọn tệp trước khi tiếp tục.')).toBeVisible(); await page.screenshot({ path: '../docs/ux/evidence/ux005-validation.png', fullPage: true });
  await page.locator('#file-upload').setInputFiles({ name: 'hop-dong.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4') }); await page.getByRole('combobox').click(); await page.getByRole('option', { name: 'Hợp đồng (HD)' }).click(); await page.getByRole('button', { name: 'Tiếp tục' }).click(); await expect(page.getByText('Loại văn bản này không yêu cầu phê duyệt.')).toBeVisible(); await page.screenshot({ path: '../docs/ux/evidence/ux005-workflow.png', fullPage: true });
  await page.getByRole('button', { name: 'Tiếp tục' }).click(); await expect(page.getByText('Người ký ngoài và thông tin bổ sung')).toBeVisible(); await page.screenshot({ path: '../docs/ux/evidence/ux005-participants.png', fullPage: true }); await page.getByRole('button', { name: 'Tiếp tục' }).click(); await expect(page.getByText('Rà soát trước khi tạo')).toBeVisible(); await expect(page.getByText('hop-dong.pdf')).toBeVisible(); await page.screenshot({ path: '../docs/ux/evidence/ux005-review.png', fullPage: true });
  const submit = page.getByRole('button', { name: 'Tiếp tục sang editor' }); await submit.dblclick(); await expect.poll(() => creates).toBe(1); await page.setViewportSize({ width: 768, height: 900 }); await page.screenshot({ path: '../docs/ux/evidence/ux005-tablet.png', fullPage: true }); await page.setViewportSize({ width: 375, height: 812 }); await page.screenshot({ path: '../docs/ux/evidence/ux005-mobile-stepper.png', fullPage: true });
});
