import { expect, test } from '@playwright/test';

async function signIn(page: import('@playwright/test').Page) { await page.addInitScript(() => window.localStorage.setItem('esign.auth', JSON.stringify({ tokens: { accessToken: 'ux008' }, user: { id: 1, email: 'user@example.test', role: 'super_admin' }, tenant: { id: 1, name: 'UX', plan: 'test', status: 'active' }, permissions: [] }))); }
const first = { id: 1, tenant_id: 1, user_id: 1, type: 'approval_request', title: 'Cần phê duyệt tài liệu', message: 'Bạn có một yêu cầu mới.', link: '/approvals/10', is_read: false, created_at: '2026-07-15T08:00:00Z' };
const second = { id: 2, tenant_id: 1, user_id: 1, type: 'sign_completed', title: 'Đã ký xong', message: 'Tài liệu đã hoàn thành.', link: '/documents/3/flow', is_read: true, created_at: '2026-07-14T08:00:00Z' };

test('UX-008 dropdown opens history and history supports read, all-read, delete and pagination', async ({ page }) => {
  await signIn(page); let pageNumber = 1; let notifications = [first, second];
  await page.route('http://127.0.0.1:4010/**', route => { const url = route.request().url(); if (url.includes('/notifications/unread-count')) return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ count: notifications.filter(n => !n.is_read).length }) }); if (url.includes('/notifications/read-all')) { notifications = notifications.map(n => ({ ...n, is_read: true })); return route.fulfill({ body: '{}' }); } if (/notifications\/1\/read/.test(url)) { notifications = notifications.map(n => n.id === 1 ? { ...n, is_read: true } : n); return route.fulfill({ body: '{}' }); } if (/notifications\/1$/.test(url) && route.request().method() === 'DELETE') { notifications = notifications.filter(n => n.id !== 1); return route.fulfill({ body: '{}' }); } if (url.includes('/notifications?')) { const current = new URL(url).searchParams.get('page'); pageNumber = Number(current || 1); return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ notifications: pageNumber === 1 ? notifications : [second], total: 25, page: pageNumber, limit: 20, totalPages: 2 }) }); } return route.fulfill({ contentType: 'application/json', body: JSON.stringify([]) }); });
  await page.goto('/'); await page.getByRole('button', { name: 'Mở thông báo' }).click(); await page.getByRole('link', { name: 'Xem tất cả thông báo' }).click(); await expect(page).toHaveURL(/\/notifications$/); await expect(page.getByText('Chưa đọc')).toBeVisible(); await page.screenshot({ path: '../docs/ux/evidence/ux008-history-desktop.png', fullPage: true });
  await page.locator('article').first().getByLabel('Đánh dấu đã đọc').click(); await expect(page.getByText('Đã đánh dấu thông báo là đã đọc.')).toBeVisible(); await page.getByRole('button', { name: 'Sau' }).click(); await expect.poll(() => pageNumber).toBe(2); await page.setViewportSize({ width: 768, height: 900 }); await page.screenshot({ path: '../docs/ux/evidence/ux008-history-tablet.png', fullPage: true }); await page.setViewportSize({ width: 375, height: 812 }); await page.screenshot({ path: '../docs/ux/evidence/ux008-history-mobile.png', fullPage: true });
});

test('UX-008 history resolves error, retry and empty states without backend details', async ({ page }) => {
  await signIn(page); let failed = true;
  await page.route('http://127.0.0.1:4010/**', route => { const pathname = new URL(route.request().url()).pathname; return route.fulfill({ status: pathname.endsWith('/notifications') && failed ? 500 : 200, contentType: 'application/json', body: JSON.stringify(pathname.endsWith('/notifications') ? (failed ? { error: { message: 'tenant secret' } } : { notifications: [], total: 0, page: 1, limit: 20, totalPages: 0 }) : { count: 0 }) }); });
  await page.goto('/notifications'); const error = page.locator('[role="alert"]').filter({ hasText: 'Không thể tải lịch sử thông báo' }); await expect(error).toBeVisible(); await expect(page.locator('body')).not.toContainText('tenant secret'); failed = false; await error.getByRole('button', { name: 'Thử lại' }).click(); await expect(page.getByText('Chưa có thông báo')).toBeVisible();
});
