'use client';
import { useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Download, FilePlus2, Files, MoreHorizontal } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '@/components/providers/auth-provider';
import { Button } from '@/components/ui/button';
type Attachment = { id:number; file_name:string; file_size:string|null; uploaded_at:string; attachment_kind:string; status:string; withdraw_reason?:string|null; uploaded_by?:{full_name?:string|null;email:string}|null };
const base64=(f:File)=>new Promise<string>((yes,no)=>{const r=new FileReader();r.onload=()=>yes(String(r.result).split(',')[1]||'');r.onerror=no;r.readAsDataURL(f)});
export function DossierAttachments({documentId}:{documentId:number}){const{fetchJson}=useAuth(),input=useRef<HTMLInputElement>(null),[uploading,setUploading]=useState(false);const{data,refetch,isLoading}=useQuery({queryKey:['dossier-attachments',documentId],queryFn:()=>fetchJson<{attachments:Attachment[];can_upload:boolean}>(`/documents/${documentId}/attachments`)});const upload=async(f?:File)=>{if(!f)return;setUploading(true);try{await fetchJson(`/documents/${documentId}/attachments`,{method:'POST',body:JSON.stringify({file_name:f.name,file_base64:await base64(f),file_type:f.type,attachment_kind:'SUPPLEMENTAL'})});toast.success('Đã thêm tài liệu');await refetch()}catch(e:any){toast.error(e.message||'Không thể tải tệp')}finally{setUploading(false);if(input.current)input.current.value=''}};const withdraw=async(a:Attachment)=>{const reason=window.prompt(`Lý do thu hồi “${a.file_name}”`);if(!reason?.trim())return;try{await fetchJson(`/documents/${documentId}/attachments/${a.id}/withdraw`,{method:'POST',body:JSON.stringify({reason})});toast.success('Đã thu hồi tài liệu');await refetch()}catch(e:any){toast.error(e.message||'Không thể thu hồi')}};return <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><Files className="h-4 w-4"/>Tài liệu bổ sung</h2>{data?.can_upload&&<><input ref={input} className="sr-only" type="file" onChange={e=>upload(e.target.files?.[0])}/><Button size="sm" variant="outline" onClick={()=>input.current?.click()} disabled={uploading}><FilePlus2 className="mr-2 h-4 w-4"/>{uploading?'Đang tải...':'Thêm tệp'}</Button></>}</div><div className="space-y-2">{isLoading?<p className="text-sm text-slate-500">Đang tải...</p>:data?.attachments.map(a=><div key={a.id} className={`rounded-lg border p-3 ${a.status==='WITHDRAWN'?'opacity-55':''}`}><div className="flex justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-medium">{a.file_name}</p><p className="text-xs text-slate-500">{a.status==='WITHDRAWN'?<><b>Đã thu hồi</b>{a.withdraw_reason?` · Lý do: ${a.withdraw_reason}`:''}</>:a.attachment_kind}</p></div>{a.status==='ACTIVE'&&<div className="flex"><a className="p-2" href={`/api-proxy/documents/${documentId}/attachments/${a.id}/download`}><Download className="h-4 w-4"/></a><Button size="icon" variant="ghost" onClick={()=>withdraw(a)} title="Thu hồi tài liệu"><MoreHorizontal className="h-4 w-4"/></Button></div>}</div></div>)}</div></section>}
